---
title: "Analisis descriptivo clonazepam"
author: "Andrés E. Arguedas L."
date: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
x <- c("ggplot2", "scales", "gridExtra", "grid", "magrittr", "plyr")
sapply(x, library, character.only = T)
remove(x)
clon <- readRDS(file = "F:/Proyecto enfermeria/Practica-Enfermeria/data/clonazepam.rds")
clon$edad.rec <- cut(clon$edad, breaks = c(-Inf, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, Inf), labels = c("0 a 10", "11 a 15", "16 a 20", "21 a 25", "26 a 30", "31 a 35", "36 a 40", "41 a 45", "46 a 50", "51 a 55", "56 a 60", "61 a 65", "66 a 70", "71 a 75", "76 a 80", "81 a 85", "86 a 90", "Más de 91"))
clon.na <- na.omit(clon)
```

```{r pastel, echo = F}
mujeres <- sum(clon.na$sexo == 2) / nrow(clon.na)
hombres <- sum(clon.na$sexo == 1) / nrow(clon.na)

df1 <- data.frame(
  sexo = c("Hombres", "Mujeres"),
  porcentaje = c(hombres, mujeres)
)

bp <- ggplot(df1, aes(x = "", y = porcentaje, fill = sexo)) + geom_bar(width = 1, stat = "identity")
pie <- bp + coord_polar("y", start = 0)

blank_theme <- theme_minimal()+
  theme(
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  panel.border = element_blank(),
  panel.grid=element_blank(),
  axis.ticks = element_blank(),
  plot.title=element_text(size=14, face="bold")
  )

pie <- pie + scale_fill_manual(values = c("brown2", "blue3"), name = "Sexo") +  blank_theme +
  theme(axis.text.x=element_blank(), plot.title = element_text(hjust = 0.5)) +
  geom_text(aes(y = c(cumsum(porcentaje)[-length(porcentaje)] + .5, cumsum(porcentaje)[-length(porcentaje)]), 
            label = percent(porcentaje)), size=5) + ggtitle("Gráfico N° 1:\nPrescripciones de clonazepam por sexo")

g <- arrangeGrob(pie, bottom = textGrob("Fuente: Datos de consumo de psicotrópicos de la CCSS", x = 0, hjust = -0.1, vjust = -0.1, gp = gpar(fontsize = 10)))

grid.draw(g)
```

```{r piramide, echo = F, warning = F}
clon.sexoedad <- aggregate(x = clon.na, by = list(Edad = clon.na$edad.rec, Sexo = clon.na$sexo), FUN = length)[, 1:3]
clon.sexoedad$ID <- ifelse(clon.sexoedad$Sexo == 1, clon.sexoedad$ID / 237900 * 100, clon.sexoedad$ID / 463895 * 100)
clon.sexoedad$ID <- ifelse(clon.sexoedad$Sexo == 1, -1 * clon.sexoedad$ID, clon.sexoedad$ID)
colnames(clon.sexoedad)[3] <- "Prescripciones"

piramide <- ggplot(clon.sexoedad, aes(x = Edad, y = Prescripciones, fill = Sexo)) + 
                   geom_bar(subset = .(Sexo == 1), stat = "identity") +
                   geom_bar(subset = .(Sexo == 2), stat = "identity") +
                   coord_flip() +
                   theme_minimal()+
                   theme(plot.title = element_text(size = 14, face = "bold", hjust = 0.5),
                         panel.grid.minor.y=element_blank(),
                         panel.grid.major.y=element_blank()) +
                   scale_fill_brewer(palette = "Set1", labels = c("Hombres", "Mujeres")) +
                   scale_y_continuous(limits = c(-12.5, 12.5), breaks = seq(-10, 10, 5), 
                                      labels = c("10", "5", "0", "5", "10")) +
                   xlab("Edad") +
                   ylab("Porcentaje") +
                   ggtitle("Gráfico N° 2:\nPorcentaje del total de prescripciones por grupos de edad y sexo")
                   

g <- arrangeGrob(piramide, bottom = textGrob("Fuente: Datos de consumo de psicotrópicos de la CCSS", x = 0, hjust = -0.1, vjust = -0.1, gp = gpar(fontsize = 10)))

grid.draw(g)
```

```{r paciente, echo = F}
clon.na$sexo %<>% as.numeric()
clon.paciente <- aggregate(x = clon.na[, c(3, 5)], by = list(ID = clon.na$ID), FUN = function(x) c(m = min(x), l = length(x)))
clon.paciente$sexo <- clon.paciente$sexo[, 1]
clon.paciente$prescripciones <- clon.paciente$edad[, 2]
clon.paciente$edad <- clon.paciente$edad[, 1]
ggplot(data = clon.paciente, aes(y = prescripciones, x = 1)) + geom_boxplot() + theme_minimal()
```

```{r serie de tiempo, echo = F}
clon.tiempo <- aggregate(x = clon.na[, 1], by = list(Mes = clon.na$mes, Año = clon.na$año), FUN = length)
ts1 <- ts(clon.tiempo$x, start = c(2011, 1), end = c(2015, 12), frequency = 12)
plot(ts1, ylab = "Prescripciones")
```

```{r}
aa <- clon.paciente$ID[which(clon.paciente$prescripciones >= 60)]
subset(clon.na, ID %in% aa)
bb <- which(hat(clon.paciente$prescripciones) > 2 * mean(hat(clon.paciente$prescripciones)))
subset(clon.na, ID %in% bb)
```

